name: Build and Deploy
on:
  push:
    branches: [main] 
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Angular 21 requires modern Node

      - name: Install and Build
        run: |
          npm install
          npx ng build --configuration production --base-href=/${{ github.event.repository.name }}/

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/${{ github.event.repository.name }}/browser # Path for Angular 17+
          branch: gh-pages